# node:14.0
image: "node@sha256:9e8704229d548d88f4b34563a6d8f359e4ecbea14f1edadacedd375273a0f9d4"

services:
  - "postgres:latest"

cache:
  paths:
    - "node_modules/"

variables:
  POSTGRES_DB: "etwindb"
  POSTGRES_USER: "runner"
  POSTGRES_PASSWORD: "dev"

before_script:
  - "node --version"
  - "npm --version"
  - "yarn --version"
  - "yarn install --quiet"
  - 'echo -e "ETWIN_DB_NAME=${POSTGRES_DB}\nETWIN_DB_USER=${POSTGRES_USER}\nETWIN_DB_PASSWORD=${POSTGRES_PASSWORD}\nETWIN_DB_HOST=postgres\nETWIN_DB_PORT=5432\nETWIN_SECRET_KEY=dev_secret\nETWIN_HTTP_PORT=50320\nETWIN_EXTERNAL_BASE_URI=http://localhost:50320\n" > .env'

stages:
  - "ci"

etwin-api-in-memory:
  stage: "ci"
  script:
    - "yarn --cwd packages/etwin-api-in-memory run test"

etwin-api-types:
  stage: "ci"
  script:
    - "yarn --cwd packages/etwin-api-types run test"

etwin-email-template:
  stage: "ci"
  script:
    - "yarn --cwd packages/etwin-email-template run test"

etwin-pg:
  stage: "ci"
  script:
    - "yarn --cwd packages/etwin-pg run prestart"

http-hammerfest:
  stage: "ci"
  script:
    - "yarn --cwd packages/http-hammerfest run test"

in-memory-email:
  stage: "ci"
  script:
    - "yarn --cwd packages/in-memory-email run test"

in-memory-hammerfest:
  stage: "ci"
  script:
    - "yarn --cwd packages/in-memory-hammerfest run test"

json-email-template:
  stage: "ci"
  script:
    - "yarn --cwd packages/json-email-template run test"

local-config:
  stage: "ci"
  script:
    - "yarn --cwd packages/local-config run test"

pg-auth:
  stage: "ci"
  script:
    - "yarn --cwd packages/pg-auth run test"

pg-user:
  stage: "ci"
  script:
    - "yarn --cwd packages/pg-user run test"

rest-server:
  stage: "ci"
  script:
    - "yarn --cwd packages/rest-server run test"

scrypt-password:
  stage: "ci"
  script:
    - "yarn --cwd packages/scrypt-password run test"

uuid4-generator:
  stage: "ci"
  script:
    - "yarn --cwd packages/uuid4-generator run test"

website:
  stage: "ci"
  script:
    - 'yarn --cwd packages/website run main:build'
