# demurgos/node:latest
image: "demurgos/node@sha256:20621ec1c96b9bd7f838c179df96c50295c3f119e428477ce501715d76bb81f7"

services:
  - "postgres:latest"

cache:
  paths:
    - ".cache/sccache/"
    - ".cargo/bin/"
    - ".cargo/registry/index/"
    - ".cargo/registry/cache/"
    - ".cargo/git/db/"
    - "node_modules/"
    - "target/"

variables:
  CARGO_HOME: ".cargo"
  POSTGRES_DB: "etwindb"
  POSTGRES_USER: "etwin"
  POSTGRES_PASSWORD: "dev"
  SCCACHE_DIR: ".cache/sccache"
  RUSTC_WRAPPER: "sccache"

before_script:
  - "node --version"
  - "yarn --version"
  - "rustc --version"
  - "cargo --version"
  - "cargo fmt --version"
  - "cargo clippy --version"
  - "yarn install --immutable"
  - |
    cat >etwin.toml <<EOL
    [etwin]
    api = "postgres"
    secret = "dev_secret"
    http_port = 50320
    external_uri = "http://localhost:50320"

    [db]
    host = "postgres"
    port = 5432
    name = "${POSTGRES_DB}"
    user = "${POSTGRES_USER}"
    password = "${POSTGRES_PASSWORD}"

    [clients.eternalfest]
    display_name = "Eternalfest"
    app_uri = "http://localhost:50313"
    callback_uri = "http://localhost:50313/oauth/callback"
    secret = "eternalfest_secret"

    [auth.twinoid]
    client_id = "380"
    secret = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

    [forum]
    posts_per_page = 10
    threads_per_page = 20

    [forum.sections.fr_main]
    display_name = "Forum Général"
    locale = "fr-FR"
    EOL

stages:
  - "ci"

ci:
  stage: "ci"
  script:
    - "cargo fmt -- --check"
#    - "cargo clippy --all-targets --all-features -- -D warnings"
    - "cargo test --no-fail-fast -- -Z unstable-options --report-time"
    - "yarn run lint"
    - "yarn run test"
    - 'yarn --cwd packages/rest-server run main:build'
    - 'yarn --cwd packages/website run build'
