# demurgos/node:14
image: "demurgos/node@sha256:6112dd5193b5d0c6f521f3eb0b4031710899e3866b72b308ae67f83210978e26"

services:
  - "postgres:latest"

cache:
  paths:
    - "node_modules/"

variables:
  POSTGRES_DB: "etwindb"
  POSTGRES_USER: "runner"
  POSTGRES_PASSWORD: "dev"

before_script:
  - "node --version"
  - "npm --version"
  - "yarn --version"
  - "rustup --version"
  - "cargo --version"
  - "rustc --version"
  - "yarn install --quiet"
  - 'echo -e "ETWIN_DB_NAME=${POSTGRES_DB}\nETWIN_DB_USER=${POSTGRES_USER}\nETWIN_DB_PASSWORD=${POSTGRES_PASSWORD}\nETWIN_DB_HOST=postgres\nETWIN_DB_PORT=5432\nETWIN_SECRET_KEY=dev_secret\nETWIN_HTTP_PORT=50320\nETWIN_EXTERNAL_BASE_URI=http://localhost:50320\n" > .env'

stages:
  - "ci"

ci:
  stage: "ci"
  script:
    - "yarn run lint"
    - "yarn --cwd packages/auth-in-memory run test"
    - "yarn --cwd packages/auth-pg run test"
    - "yarn --cwd packages/core run test"
    - "yarn --cwd packages/email-in-memory run test"
    - "yarn --cwd packages/email-template-etwin run test"
    - "yarn --cwd packages/email-template-json run test"
    - "yarn --cwd packages/etwin-client-in-memory run test"
    - "yarn --cwd packages/etwin-pg run prestart"
    - "yarn --cwd packages/hammerfest-http run test"
    - "yarn --cwd packages/hammerfest-in-memory run test"
    - "yarn --cwd packages/local-config run test"
    - "yarn --cwd packages/oauth-client-http run test"
    - "yarn --cwd packages/oauth-provider-in-memory run test"
    - "yarn --cwd packages/oauth-provider-pg run test"
    - "yarn --cwd packages/password-scrypt run test"
    - "yarn --cwd packages/rest-server run test"
    - "yarn --cwd packages/twinoid-client-http run test"
    - "yarn --cwd packages/twinoid-core run test"
    - "yarn --cwd packages/user-in-memory run test"
    - "yarn --cwd packages/user-pg run test"
    - "yarn --cwd packages/uuid4-generator run test"
    - 'yarn --cwd packages/website run main:build'
