[package]
name = "etwin_native"
version = "0.1.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "Native node bindings for Eternal-Twin"
license = "AGPL-3.0-or-later"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]
publish = false

[lib]
name = "etwin_native"
crate-type = ["cdylib"]
test = false

[build-dependencies]
neon-build = "^0.7.0"

[dependencies]
chrono = "^0.4.19"
etwin_core = { path = "../../../crates/core", features = ["neon", "serde"] }
etwin_dinoparc_client = { path = "../../../crates/dinoparc_client", features = ["neon"] }
etwin_dinoparc_store = { path = "../../../crates/dinoparc_store", features = ["neon"] }
etwin_hammerfest_client = { path = "../../../crates/hammerfest_client", features = ["neon"] }
etwin_hammerfest_store = { path = "../../../crates/hammerfest_store", features = ["neon"] }
etwin_link_store = { path = "../../../crates/link_store", features = ["neon"] }
etwin_password = { path = "../../../crates/password", features = ["neon"] }
etwin_twinoid_store = { path = "../../../crates/twinoid_store", features = ["neon"] }
etwin_user_store = { path = "../../../crates/user_store", features = ["neon"] }
neon = { version = "^0.7.0", default-features = false, features = ["event-queue-api", "napi-runtime"] }
sqlx = { version = "^0.5.1", default-features = false, features = ["macros", "chrono", "offline", "postgres", "runtime-tokio-rustls", "uuid"] }
serde = { version = "^1.0.123", features = ["derive"] }
serde_json = "^1.0.61"
tokio = { version = "^1.1.1", features = ["full"] }
once_cell = "^1.5.2"
