[package]
name = "etwin_native"
version = "0.1.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "Native node bindings for Eternal-Twin"
license = "AGPL-3.0-or-later"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]
publish = false

[lib]
name = "etwin_native"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.6.0"

[dependencies]
etwin_core = { path = "../../../crates/core", features = ["neon", "serde"] }
etwin_dinoparc_store = { path = "../../../crates/dinoparc_store", features = ["neon"] }
neon = { version = "^0.6.0", default-features = false, features = ["event-handler-api", "legacy-runtime"] }
serde_json = "^1.0.60"
tokio = { version = "^0.2.23", features = ["full"] }
once_cell = "^1.5.2"
