[package]
name = "etwin_native"
version = "0.1.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "Native node bindings for Eternal-Twin"
license = "AGPL-3.0-or-later"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]
publish = false

[lib]
name = "etwin_native"
crate-type = ["cdylib"]
test = false

[build-dependencies]
neon-build = "0.6.0"

[dependencies]
etwin_core = { path = "../../../crates/core", features = ["neon", "serde"] }
etwin_dinoparc_store = { path = "../../../crates/dinoparc_store", features = ["neon"] }
neon = { git = "https://github.com/neon-bindings/neon.git", rev = "ab9ff258cdf86d9622d552073efe034602c16301", default-features = false, features = ["napi-runtime"] }
sqlx = { version = "^0.4.1", default-features = false, features = ["macros", "chrono", "offline", "postgres", "runtime-tokio-rustls", "uuid"] }
serde_json = "^1.0.60"
tokio = { version = "^0.2.23", features = ["full"] }
once_cell = "^1.5.2"
