[package]
name = "etwin_squirrel"
version = "0.0.1"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "Manager for SQL schemas"
documentation = "https://github.com/eternal-twin/etwin"
homepage = "https://github.com/eternal-twin/etwin"
repository = "https://github.com/eternal-twin/etwin"
readme = "./README.md"
keywords = ["etwin"]
license = "AGPL-3.0-or-later"
edition = "2018"

[dependencies]
futures-util = "^0.3.12"
include_dir = "^0.6.0"
once_cell = "^1.5.2"
petgraph = "^0.5.1"
regex = "^1.4.3"
serde = { version = "^1.0.123", default-features = false, features = ["derive"] }
serde_json = { version = "^1.0.61" }
sqlx = { version = "^0.5.1", default-features = false, features = ["offline", "postgres", "runtime-tokio-rustls"] }
tokio = { version = "^1.1.1" }
